[package]
name = "day1"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = {workspace = true}
anyhow = {workspace = true}
lazy_static = {workspace = true}

[dependencies.utils]
path = "../utils"