[package]
name = "day5"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = {workspace = true}
tracing-test = "0.2.4"
anyhow = {workspace = true}
regex = "1.10.2"

[dependencies.utils]
path = "../utils"